apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: applications
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/sungjujjang/sungju-infra-applications.git
        revision: HEAD

        files:
          - path: "apps/*/values.yaml"

  template:
    metadata:
      name: '{{path.basename}}'

    spec:
      project: default

      sources:

        # 공통 Helm Chart
        - repoURL: https://github.com/sungjujjang/sungju-infra-applications.git
          targetRevision: HEAD
          path: charts/app

          helm:
            valueFiles:
              - '$values/{{path}}/{{filename}}'
              
        # 앱별 values.yaml
        - repoURL: https://github.com/sungjujjang/sungju-infra-applications.git
          targetRevision: HEAD
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true