apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "app.name" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "app.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}

    spec:
      containers:
        - name: {{ include "app.name" . }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}
          
          {{- if .Values.secret.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          {{- end }}